version: "3.8"

services:
  react-app:
    build: .
    ports:
      - "4500:4500"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
